#!/bin/sh
case "$1" in
	start)
		pooya-query datasource >/dev/null 2>&1 || exit 0
		pooya-per instance userdata pooya-userdata;;
	stop) :;;
	*) echo "unknown argument ${1}" 1>&2;;
esac

# vi: ts=4 noexpandtab
