name: Pooya Cloud image builder

on:
  push:
    branches:
      - main
    tags:
      - "[01].[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
jobs:
  pooya-build-matrix:
    strategy:
      matrix:
        arch: [x86_64]
        # aarch64, arm, ppc64le
    runs-on: ubuntu-24.04

    env:
      ARCHES: ${{ matrix.arch }}
      QUIET: 1
      CI_BUILD: "true"
      CI_BUILD_OUT: "build-ci/"

    steps:
      - name: Pull pooya source artifacts
        uses: actions/checkout@v4

      - name: Cache download
        uses: actions/cache@v4
        with:
          key: downloads-${{ matrix.arch }}-${{ hashFiles('bin/build-release') }}
          path: download/

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          key: ccache-${{ matrix.arch }}-${{ hashFiles('bin/build-release') }}
          path: ccache/

      - name: Prepare job environment
        run: bin/system-setup

      - name: Install job dependencies
        run: sudo apt-get install cloud-utils qemu-system openbios-ppc

      - name: disable invisible-mirror.net use
        run: echo "127.0.0.1 invisible-mirror.net" | sudo tee -a /etc/hosts

      - name: Build Pooya image
        env:
          # use tag name for tag build, or 'daily' for anything else.
          reason: "${{ github.ref_type == 'tag' && github.ref_name || 'daily' }}"
        run: bin/build-release "$reason"

      - name: Boot Pooya image (test only)
        run: bin/test-boot
        env:
          GUESTARCH: ${{ matrix.arch }}
          POWEROFF: "true"
          TIMEOUT: 1200  # Set timeout to 1200 seconds (20 minutes)
        timeout-minutes: 50  # GitHub workflow timeout as a backup

      - name: Find IMG file
        id: find-img
        run: |
          IMG_FILE=$(find build-ci/release/ -name "*.img" | head -n 1)
          echo "Found image file: $IMG_FILE"
          echo "img_file=$IMG_FILE" >> $GITHUB_OUTPUT
          echo "img_name=$(basename $IMG_FILE)" >> $GITHUB_OUTPUT

      - name: Upload IMG file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PooyaOS-${{ matrix.arch }}-image
          path: ${{ steps.find-img.outputs.img_file }}
          retention-days: 120

      # Only upload to releases if this is a tag push
      - name: Create Release
        id: create_release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find-img.outputs.img_file }}
          name: Pooya Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
